[workspace]
resolver = "2"
members = [
    "rlox_syntax",
    "rlox_parser",
    "rlox_interpreter",
    "rlox_derive",
    "rlox_derive_impl",
    "rlox_repl",
]

[workspace.dependencies]
anyhow = "1.0"
thiserror = "1.0.40"
