[workspace]
resolver = "2"
members = [
    "syntax-tree",
    "parser",
    "interpreter",
    "derive",
    "derive-impl",
    "repl",
]

[workspace.dependencies]
anyhow = "1.0"
thiserror = "1.0.40"
uuid = { version = "1.3.0", features = ["v4", "fast-rng", "macro-diagnostics"] }
